-- CreateEnum
CREATE TYPE "RecipeType" AS ENUM ('EXEC_BRIEF', 'MARKETING_ANGLES', 'COMPLIANCE_FLAGS', 'SALES_PROSPECTING', 'PRODUCT_SIGNALS');

-- AlterTable
ALTER TABLE "Topic" ADD COLUMN "recipeType" "RecipeType" NOT NULL DEFAULT 'EXEC_BRIEF';
