-- AlterTable
ALTER TABLE "Topic" ADD COLUMN IF NOT EXISTS "keywords" TEXT;
ALTER TABLE "Topic" ADD COLUMN IF NOT EXISTS "companyOrOrg" TEXT;
ALTER TABLE "Topic" ADD COLUMN IF NOT EXISTS "person" TEXT;
